/* Offline weighted Dijkstra on a compact municipal graph. No network calls. */
(function(root){
'use strict';
function unpack(p){const raw=typeof Buffer!=='undefined'?Uint8Array.from(Buffer.from(p.base64,'base64')):Uint8Array.from(atob(p.base64),c=>c.charCodeAt(0));const b=raw.buffer;return p.dtype==='<i4'?new Int32Array(b):p.dtype==='<u4'?new Uint32Array(b):p.dtype==='<f8'?new Float64Array(b):new Uint8Array(b)}
class Heap{constructor(){this.a=[]}push(d,n){let i=this.a.length;this.a.push([d,n]);while(i){const p=(i-1)>>1;if(this.a[p][0]<=d)break;this.a[i]=this.a[p];i=p}this.a[i]=[d,n]}pop(){const first=this.a[0],last=this.a.pop();if(this.a.length){let i=0;while(2*i+1<this.a.length){let c=2*i+1;if(c+1<this.a.length&&this.a[c+1][0]<this.a[c][0])c++;if(this.a[c][0]>=last[0])break;this.a[i]=this.a[c];i=c}this.a[i]=last}return first}}
class ForestRouter{
 constructor(data){this.data=data;for(const n of ['nodes','uv','lengths','kinds','offsets','geometry','csr_offsets','csr_nodes','csr_edges','components'])this[n]=unpack(data[n]);this.index=new Map();for(let e=0;e<data.edge_count;e++){if(this.kinds[e]===2)continue;let minx=Infinity,miny=Infinity,maxx=-Infinity,maxy=-Infinity;for(let i=this.offsets[e];i<this.offsets[e+1];i++){const x=this.geometry[2*i]/100,y=this.geometry[2*i+1]/100;minx=Math.min(minx,x);miny=Math.min(miny,y);maxx=Math.max(maxx,x);maxy=Math.max(maxy,y)}for(let x=Math.floor(minx/1000);x<=Math.floor(maxx/1000);x++)for(let y=Math.floor(miny/1000);y<=Math.floor(maxy/1000);y++){const k=x+','+y;if(!this.index.has(k))this.index.set(k,[]);this.index.get(k).push(e)}}}
 points(e){const p=[];for(let i=this.offsets[e];i<this.offsets[e+1];i++)p.push([this.geometry[2*i]/100,this.geometry[2*i+1]/100]);return p}
 project(p,e){const a=this.points(e);let best=null,s=0;for(let i=1;i<a.length;i++){const x=a[i-1],y=a[i],dx=y[0]-x[0],dy=y[1]-x[1],l=Math.hypot(dx,dy),t=l?Math.max(0,Math.min(1,((p[0]-x[0])*dx+(p[1]-x[1])*dy)/(l*l))):0,q=[x[0]+t*dx,x[1]+t*dy],d=Math.hypot(q[0]-p[0],q[1]-p[1]);if(!best||d<best.d)best={e,d,s:s+t*l,q};s+=l}best.s=s?best.s/s*this.lengths[e]:0;return best}
 access(p,allowance){const candidates=new Set();for(let x=Math.floor((p[0]-allowance)/1000);x<=Math.floor((p[0]+allowance)/1000);x++)for(let y=Math.floor((p[1]-allowance)/1000);y<=Math.floor((p[1]+allowance)/1000);y++)for(const e of this.index.get(x+','+y)||[])candidates.add(e);const best=new Map();for(const e of candidates){const q=this.project(p,e);if(q.d>allowance+1e-6)continue;const c=this.components[this.uv[e*2]],prev=best.get(c);if(!prev||q.d<prev.d-1e-9||(Math.abs(q.d-prev.d)<1e-9&&e<prev.e))best.set(c,q)}return best}
 search(a,b){const n=this.data.node_count,dist=new Float64Array(n);dist.fill(Infinity);const pred=new Int32Array(n);pred.fill(-1);const pe=new Int32Array(n);pe.fill(-1);const heap=new Heap();for(const [node,cost]of [[this.uv[a.e*2],a.s],[this.uv[a.e*2+1],this.lengths[a.e]-a.s]]){if(cost<dist[node]){dist[node]=cost;heap.push(cost,node)}}let best=a.e===b.e?Math.abs(a.s-b.s):Infinity,end=-1;const targets=new Map([[this.uv[b.e*2],b.s],[this.uv[b.e*2+1],this.lengths[b.e]-b.s]]);while(heap.a.length){const [d,u]=heap.pop();if(d!==dist[u])continue;if(d>best)break;if(targets.has(u)&&d+targets.get(u)<best){best=d+targets.get(u);end=u}for(let k=this.csr_offsets[u];k<this.csr_offsets[u+1];k++){const v=this.csr_nodes[k],e=this.csr_edges[k],nd=d+this.lengths[e]*(this.kinds[e]===2?5:1);if(nd<dist[v]){dist[v]=nd;pred[v]=u;pe[v]=e;heap.push(nd,v)}}}if(!Number.isFinite(best))return null;if(end<0)return {cost:best,segments:[{e:a.e,from:a.s,to:b.s}]};const path=[];let u=end;while(pred[u]>=0){path.push({e:pe[u],from:this.uv[pe[u]*2]===pred[u]?0:this.lengths[pe[u]],to:this.uv[pe[u]*2]===u?0:this.lengths[pe[u]]});u=pred[u]}path.reverse();return {cost:best,segments:[{e:a.e,from:a.s,to:u===this.uv[a.e*2]?0:this.lengths[a.e]},...path,{e:b.e,from:end===this.uv[b.e*2]?0:this.lengths[b.e],to:b.s}]}}
 route(origin,destination,allowance=1000){if(!Number.isFinite(allowance)||allowance<0)throw Error('Walking allowance must be finite and nonnegative');const start=performance.now(),as=this.access(origin,allowance),bs=this.access(destination,allowance);let best=null;for(const [c,a]of as){const b=bs.get(c);if(!b)continue;const path=this.search(a,b);if(!path)continue;const score=path.cost+10*(a.d+b.d);if(!best||score<best.score)best={...path,score,a,b}}if(!best)return {candidate_connected:false,reason:as.size===0?'origin_access_exceeds_allowance':bs.size===0?'destination_access_exceeds_allowance':'no_shared_component',query_ms:performance.now()-start};let distance=0,gap=0,gapIds=[];for(const s of best.segments){const l=Math.abs(s.to-s.from);distance+=l;if(l>1e-6&&this.kinds[s.e]===2){gap+=l;gapIds.push(this.data.gap_ids[s.e])}}return {candidate_connected:true,field_verified:false,initial_walk_lower_bound_m:best.a.d,final_walk_lower_bound_m:best.b.d,network_distance_km:distance/1000,proposed_gap_distance_m:gap,gap_ids:gapIds,segments:best.segments,origin_attachment:best.a.q,destination_attachment:best.b.q,query_ms:performance.now()-start}}
}
root.ForestRouter=ForestRouter;if(typeof module!=='undefined')module.exports={ForestRouter};
})(typeof globalThis!=='undefined'?globalThis:this);
